"""Add return_date column to Item model

Revision ID: 735a52c6a392
Revises: 
Create Date: 2023-11-22 15:49:01.586302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735a52c6a392'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
